---
- name: Server setup and configuration
  hosts: localhost
  become: yes
  vars:
    host_name: "my-server-n1"

  tasks:
    - name: Set hostname
      command: hostnamectl set-hostname {{ host_name }}

    - name: Enable CRB repository
      command: dnf config-manager --set-enabled crb
      ignore_errors: yes

    - name: Install EPEL and utilities
      dnf:
        name:
          - epel-release
          - ansible
          - lrzsz
          - screen
          - dnf-automatic
        state: present

    - name: Enable Fastest Mirror Plugin
      ini_file:
        path: /etc/dnf/dnf.conf
        section: main
        option: fastestmirror
        value: True

    - name: Configure .vimrc
      copy:
        dest: ~/.vimrc
        content: |
          syntax on
          set autoindent
          set smartindent
          set hlsearch
          set showmatch
          set tabstop=4
          set shiftwidth=4
          set expandtab

    - name: Add alias ll to .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "alias ll='ls -alh'"
      notify:
        - reload bashrc
      when: "'alias ll' not in lookup('file', '~/.bashrc')"

    - name: Configure system messages
      copy:
        dest: "{{ item }}"
        content: |
          ***Warning***
          Authorised access only! This is a private system.
          All connections are monitored and recorded.
          Unauthorized access or use may lead to prosecution.
          Disconnect IMMEDIATELY if you are not an authorized user!
      with_items:
        - /etc/issue
        - /etc/issue.net
        - /etc/motd
      timeout: 10

    - name: Configure dnf-automatic for security updates
      lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: '^upgrade_type ='
        line: 'upgrade_type = security'
        state: present
      notify:
        - enable dnf-automatic

    - name: Enable and start dnf-automatic timer
      systemd:
        name: dnf-automatic.timer
        enabled: true
        state: started

    - name: Update system packages
      shell: |
        dnf upgrade "*" --latest --update-cache --disable-gpg-check | tee /tmp/dnf_update_output.log

  handlers:
    - name: reload bashrc
      command: bash -c "source ~/.bashrc"
      
    - name: enable dnf-automatic
      command: systemctl enable --now dnf-automatic.timer

  - name: Display reboot message
    debug:
      msg: "The system has been updated. Please consider rebooting your computer."
