LogFile = /usr/local/maldetect/logs/event_log
LogFile = /usr/local/maldetect/logs/event_log.1

Archive = /usr/local/maldetect/logs/event_log.*
Archive = /usr/local/maldetect/logs/event_log.*.gz

*ApplyStdDate="%b %e %Y %H:%M:%S"

*ExpandRepeats
