user www www;
worker_processes auto;

pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server_tokens off;
	
    include       mime.types;
    default_type  application/octet-stream;
    
    limit_req_zone $binary_remote_addr zone=req_limit_20:10m rate=20r/s;
    limit_req_zone $binary_remote_addr zone=req_limit_10:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;
    
    map $status $fail2banlog {
        ~^[23]  0;
        default 1;
    }

    access_log  /var/log/nginx/access.log;
    error_log	/var/log/nginx/error.log;
    
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1000;
    gzip_static on;

    keepalive_timeout 15s;
    client_header_timeout 10s;
    send_timeout 10s;
    client_max_body_size 10m;
    client_body_timeout 10s; 
    client_body_buffer_size  1K;
    client_header_buffer_size 1k;
    large_client_header_buffers 2 1k;
	
    more_set_headers 'X-Frame-Options "SAMEORIGIN"';
    more_set_headers 'X-XSS-Protection "1; mode=block"';
    more_set_headers 'X-Content-Type-Options "nosniff"';

    include /usr/local/nginx/conf/vhosts/*.conf;
}
