LogFile = /var/log/inotify_file_monitor.log
LogFile = /var/log/inotify_file_monitor.log.1

Archive = /var/log/inotify_file_monitor.*
Archive = /var/log/inotify_file_monitor.*.gz

*ApplyEuroDate

*ExpandRepeats
